### ISSUE TITLE
Error when sourcing

### ISSUE THREAD

**Issue by fharper** [psprint/zsh-sweep#7]
When I add

```bash
zs_set_path=1
source /Users/fharper/zsh-sweep/zsh-sweep.plugin.zsh
```

to my `~/.zshrc`, I get this error `util/zs::setup-aliases:29: scalar parameter REPLY created globally in function util/zs::setup-aliases` and the command doesn't exist, which I assume it's because the aliases weren't created.

Any idea what is causing this?

--

macOS 13.3 build 22E252 on arm64
zsh 5.9 (x86_64-apple-darwin22.0)

**Comment by jordantrizz** [comment]
Also, getting the same error.

**Comment by LangLangBart** [comment]
- warning comes from the `warncreateglobal` option

https://github.com/psprint/zsh-sweep/blob/a6f2c44cdb5791666356f7fdfc1abc1da446f54d/functions/util/zs::setup-aliases#L10-L12

Ref: [zsh manual - WARNCREATEGLOBAL](https://zsh.sourceforge.io/Doc/Release/Options.html#index-WARNCREATEGLOBAL)

> WARN_CREATE_GLOBAL
> Print a warning message when a global parameter is created in a function by an assignment or in math context. This often indicates that a parameter has not been declared local when it should have been. Parameters explicitly declared global from within a function using typeset -g do not cause a warning. Note that there is no warning when a local parameter is assigned to in a nested function, which may also indicate an error.

---

- silence the warning (or remove the `warncreateglobal` option)

```diff
--- a/functions/util/zs::setup-aliases
+++ b/functions/util/zs::setup-aliases
@@ -26,6 +26,7 @@ if [[ ! -d $ZSAES ]];then
 fi

 local DIR dirs=($ZSAES $ZSAES/checks $ZSAES/results)
+typeset -g REPLY

 for DIR ($dirs);do
     # Set up aliases (global, suffix and the proper ones)
```

**Comment by psprint** [comment]
I've merged a  fix.
